package net.attackstudioyt.lunascosmetics.client.theme;

import net.attackstudioyt.lunascosmetics.LunasCosmetics;
import net.attackstudioyt.lunascosmetics.client.ClientConfig;
import net.attackstudioyt.lunascosmetics.client.mixin.CursorAccessor;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.cursor.Cursor;
import net.minecraft.client.gui.cursor.StandardCursors;
import net.minecraft.client.texture.NativeImage;
import net.minecraft.util.Identifier;
import org.lwjgl.glfw.GLFW;
import org.lwjgl.glfw.GLFWImage;
import org.lwjgl.system.MemoryStack;
import org.lwjgl.system.MemoryUtil;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;

/**
 * The Cherry Cat theme. Every vanilla GUI sprite/texture that has a pink twin (listed in
 * theme_index.txt, generated by tools/theme_sprites.py) is swapped at draw time, so the
 * theme flips on and off instantly with no resource reload. Also owns the paw cursors.
 */
public final class Theme {
    private Theme() {
    }

    private static final Map<Identifier, Identifier> SPRITES = new HashMap<>();
    private static final Map<Identifier, Identifier> TEXTURES = new HashMap<>();
    private static Cursor pawArrow;
    private static Cursor pawHand;
    private static boolean cursorsTried;

    public static boolean on() {
        return ClientConfig.get().theme;
    }

    public static void load() {
        try (InputStream in = Theme.class.getResourceAsStream("/assets/lunascosmetics/theme_index.txt")) {
            if (in == null) {
                return;
            }
            BufferedReader r = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = r.readLine()) != null) {
                line = line.trim();
                if (line.startsWith("sprite ")) {
                    String p = line.substring(7);
                    SPRITES.put(Identifier.ofVanilla(p), Identifier.of(LunasCosmetics.MOD_ID, "theme/" + p));
                } else if (line.startsWith("texture ")) {
                    String p = line.substring(8);
                    TEXTURES.put(Identifier.ofVanilla("textures/gui/" + p),
                            Identifier.of(LunasCosmetics.MOD_ID, "textures/theme/gui/" + p));
                }
            }
        } catch (Exception e) {
            LunasCosmetics.LOGGER.warn("theme index unreadable: {}", e.toString());
        }
    }

    public static Identifier sprite(Identifier id) {
        if (id == null || !on()) {
            return id;
        }
        return SPRITES.getOrDefault(id, id);
    }

    public static Identifier texture(Identifier id) {
        if (id == null || !on()) {
            return id;
        }
        return TEXTURES.getOrDefault(id, id);
    }

    /** Swaps the arrow and pointing hand for paws while a themed menu is open. */
    public static Cursor cursor(Cursor wanted) {
        if (!on() || MinecraftClient.getInstance().currentScreen == null) {
            return wanted;
        }
        if (!cursorsTried) {
            cursorsTried = true;
            pawArrow = load("pointer", 0, 0);
            pawHand = load("hand", 10, 2);
        }
        if ((wanted == Cursor.DEFAULT || wanted == StandardCursors.ARROW) && pawArrow != null) {
            return pawArrow;
        }
        if (wanted == StandardCursors.POINTING_HAND && pawHand != null) {
            return pawHand;
        }
        return wanted;
    }

    private static Cursor load(String name, int hotX, int hotY) {
        try (InputStream in = Theme.class.getResourceAsStream("/assets/lunascosmetics/textures/cursor/" + name + ".png")) {
            NativeImage img = NativeImage.read(in);
            int w = img.getWidth(), h = img.getHeight();
            ByteBuffer pixels = MemoryUtil.memAlloc(w * h * 4);
            for (int y = 0; y < h; y++) {
                for (int x = 0; x < w; x++) {
                    int argb = img.getColorArgb(x, y);
                    pixels.put((byte) (argb >> 16)).put((byte) (argb >> 8)).put((byte) argb).put((byte) (argb >>> 24));
                }
            }
            pixels.flip();
            long handle;
            try (MemoryStack stack = MemoryStack.stackPush()) {
                GLFWImage image = GLFWImage.malloc(stack);
                image.set(w, h, pixels);
                handle = GLFW.glfwCreateCursor(image, hotX * 2, hotY * 2);
            }
            MemoryUtil.memFree(pixels);
            img.close();
            return handle == 0 ? null : CursorAccessor.create("lunascosmetics_" + name, handle);
        } catch (Exception e) {
            LunasCosmetics.LOGGER.warn("paw cursor {} failed: {}", name, e.toString());
            return null;
        }
    }
}
