package net.attackstudioyt.lunascosmetics.client.theme;

import com.mojang.blaze3d.platform.NativeImage;
import net.attackstudioyt.lunascosmetics.LunasCosmetics;
import net.attackstudioyt.lunascosmetics.client.ClientConfig;
import net.minecraft.client.Minecraft;
import net.minecraft.resources.ResourceLocation;
import org.lwjgl.glfw.GLFW;
import org.lwjgl.glfw.GLFWImage;
import org.lwjgl.system.MemoryStack;
import org.lwjgl.system.MemoryUtil;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;

/**
 * The Cherry Cat theme. Every vanilla GUI sprite/texture that has a pink twin (listed in
 * theme_index.txt, generated by tools/theme_sprites.py) is swapped at draw time, so the
 * theme flips on and off instantly with no resource reload. Also owns the paw cursor
 * (1.21.1 has no cursor API, so it's set straight through GLFW while a menu is open).
 */
public final class Theme {
    private Theme() {
    }

    private static final Map<ResourceLocation, ResourceLocation> SPRITES = new HashMap<>();
    private static final Map<ResourceLocation, ResourceLocation> TEXTURES = new HashMap<>();
    private static long pawCursor;
    private static boolean cursorTried;
    private static boolean cursorShown;

    public static boolean on() {
        return ClientConfig.get().theme;
    }

    public static void load() {
        try (InputStream in = Theme.class.getResourceAsStream("/assets/lunascosmetics/theme_index.txt")) {
            if (in == null) {
                return;
            }
            BufferedReader r = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = r.readLine()) != null) {
                line = line.trim();
                if (line.startsWith("sprite ")) {
                    String p = line.substring(7);
                    SPRITES.put(ResourceLocation.withDefaultNamespace(p),
                            ResourceLocation.fromNamespaceAndPath(LunasCosmetics.MOD_ID, "theme/" + p));
                } else if (line.startsWith("texture ")) {
                    String p = line.substring(8);
                    TEXTURES.put(ResourceLocation.withDefaultNamespace("textures/gui/" + p),
                            ResourceLocation.fromNamespaceAndPath(LunasCosmetics.MOD_ID, "textures/theme/gui/" + p));
                }
            }
        } catch (Exception e) {
            LunasCosmetics.LOGGER.warn("theme index unreadable: {}", e.toString());
        }
    }

    public static ResourceLocation sprite(ResourceLocation id) {
        if (id == null || !on()) {
            return id;
        }
        return SPRITES.getOrDefault(id, id);
    }

    public static ResourceLocation texture(ResourceLocation id) {
        if (id == null || !on()) {
            return id;
        }
        return TEXTURES.getOrDefault(id, id);
    }

    /** Called every frame: paw cursor while a themed menu is open, normal arrow otherwise. */
    public static void updateCursor() {
        Minecraft mc = Minecraft.getInstance();
        boolean want = on() && mc.screen != null;
        if (want == cursorShown) {
            return;
        }
        if (want && !cursorTried) {
            cursorTried = true;
            pawCursor = loadCursor("pointer", 0, 0);
        }
        long window = mc.getWindow().getWindow();
        GLFW.glfwSetCursor(window, want ? pawCursor : 0L);
        cursorShown = want;
    }

    private static long loadCursor(String name, int hotX, int hotY) {
        try (InputStream in = Theme.class.getResourceAsStream("/assets/lunascosmetics/textures/cursor/" + name + ".png")) {
            NativeImage img = NativeImage.read(in);
            int w = img.getWidth(), h = img.getHeight();
            ByteBuffer pixels = MemoryUtil.memAlloc(w * h * 4);
            for (int y = 0; y < h; y++) {
                for (int x = 0; x < w; x++) {
                    int abgr = img.getPixelRGBA(x, y); // NativeImage stores ABGR
                    pixels.put((byte) abgr).put((byte) (abgr >> 8)).put((byte) (abgr >> 16)).put((byte) (abgr >>> 24));
                }
            }
            pixels.flip();
            long handle;
            try (MemoryStack stack = MemoryStack.stackPush()) {
                GLFWImage image = GLFWImage.malloc(stack);
                image.set(w, h, pixels);
                handle = GLFW.glfwCreateCursor(image, hotX * 2, hotY * 2);
            }
            MemoryUtil.memFree(pixels);
            img.close();
            return handle;
        } catch (Exception e) {
            LunasCosmetics.LOGGER.warn("paw cursor {} failed: {}", name, e.toString());
            return 0L;
        }
    }
}
